import csv
import os

CSV_PATH = r'C:\Users\Gaurav Batule\Documents\antigravity\serene-davinci\ui-ux-pro-max-skill\src\ui-ux-pro-max\data\styles.csv'

DESIGN_LANGUAGES_29 = [
    {
        "name": "Minimalism",
        "category": "Minimalism",
        "type": "General",
        "keywords": "Clean, spacious, white space, reductionist, essential elements, functional simplicity, high contrast, uncluttered",
        "primary": "Monochromatic, Neutral Whites #FFFFFF, Deep Black #0A0A0A",
        "secondary": "Soft Greys #E5E7EB, #6B7280, Single crisp accent",
        "effects": "Subtle 150-200ms opacity fades, crisp 1px hairlines, zero decorative clutter",
        "best_for": "SaaS tools, enterprise dashboards, reading apps, high-end portfolios, documentation",
        "do_not_use": "Gaming apps, maximalist artistic showcases, chaotic brands",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "✓ WCAG AAA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10", "era": "1960s Modernism", "complexity": "Low",
        "prompt": "Design an ultra-clean minimalist interface with generous white space, strong typographic hierarchy, zero drop shadows, and essential elements only.",
        "css": "display: grid; gap: 2rem; max-width: 1200px; color: #0a0a0a; background: #ffffff; border: 1px solid rgba(0,0,0,0.08);",
        "checklist": "☐ Generous negative space, ☐ Minimal color palette, ☐ WCAG AAA contrast, ☐ Fast loading, ☐ Essential UI only",
        "vars": "--bg: #ffffff, --text: #0a0a0a, --border-hairline: rgba(0,0,0,0.08), --font-sans: 'Inter', sans-serif"
    },
    {
        "name": "Maximalism",
        "category": "Maximalism",
        "type": "Creative",
        "keywords": "Rich, bold, dense, layered patterns, vibrant colors, expressive typography, sensory overload, eclectic, ornate",
        "primary": "Vivid Magenta #EC4899, Electric Cyan #06B6D4, Radiant Yellow #FACC15, Deep Violet #7C3AED",
        "secondary": "Contrasting clashing accents, textured gradients, multi-hue overlays",
        "effects": "Animated marquee, multi-layer parallax, glowing hover states, overlapping z-index cards",
        "best_for": "Music festivals, fashion brands, creative agency portfolios, youth entertainment",
        "do_not_use": "Enterprise B2B platforms, healthcare applications, government portals",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚠ Moderate", "a11y": "⚠ Requires Care", "mobile": "◐ Medium", "conv": "◐ Medium",
        "framework": "Tailwind 9/10, GSAP 10/10, Framer Motion 10/10", "era": "1970s Postmodern", "complexity": "High",
        "prompt": "Create an energetic maximalist interface with bold clashing colors, layered typography, vibrant decorative textures, and expressive motion.",
        "css": "background: linear-gradient(135deg, #ec4899, #7c3aed, #06b6d4); font-size: clamp(2rem, 8vw, 6rem); mix-blend-mode: difference;",
        "checklist": "☐ Layered visual elements, ☐ High visual energy, ☐ Expressive typography pairings, ☐ Controlled chaotic composition",
        "vars": "--color-p1: #ec4899, --color-p2: #7c3aed, --color-p3: #06b6d4, --font-display: 'Clash Display', bold"
    },
    {
        "name": "Swiss Design",
        "category": "Swiss Design",
        "type": "Editorial & Structural",
        "keywords": "International Typographic Style, asymmetric grid, objective clarity, sans-serif, mathematical proportion, hairline rules",
        "primary": "Stark Black #000000, Pure White #FFFFFF, Helvetica Red #E11D48",
        "secondary": "Cold Slate #64748B, Neutral Grey #F1F5F9, Signal Blue #2563EB",
        "effects": "1px hairline architectural rules, zero blurred drop shadows, crisp modular rhythm, monospaced coordinates",
        "best_for": "Scientific tools, forensic software, institutional portals, technical dashboards, luxury design systems",
        "do_not_use": "Playful children's games, kitschy decorative projects",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "✓ WCAG AAA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10, Vanilla CSS 10/10", "era": "1950s Swiss Style", "complexity": "Low-Medium",
        "prompt": "Design a Swiss Typographic interface adhering to the International Typographic Style: asymmetric grid ratios (5/7 or 4/8), 1px hairline rules, objective sans-serif typography, and restrained signal red accents.",
        "css": "display: grid; grid-template-columns: repeat(12, 1fr); border: 1px solid rgba(255,255,255,0.08); font-family: 'Inter', Helvetica, sans-serif; letter-spacing: -0.02em;",
        "checklist": "☐ Strict mathematical grid, ☐ 1px architectural hairline rules, ☐ Objective sans-serif hierarchy, ☐ Paper + Ink + Accent model",
        "vars": "--bg-canvas: #090a0f, --hairline: rgba(255,255,255,0.08), --font-sans: 'Inter', --font-mono: 'JetBrains Mono', --accent: #ef4444"
    },
    {
        "name": "Neo-Brutalism",
        "category": "Neo-Brutalism",
        "type": "General",
        "keywords": "Thick black borders (2-4px), hard drop shadows (4px 4px 0px #000), bright saturated colors, playful geometry, high contrast",
        "primary": "Canary Yellow #FDE047, Neo Green #86EFAC, Electric Violet #C084FC, Bold Coral #FB7185",
        "secondary": "Pure Black #000000 borders, Off-White #FEFCE8 background",
        "effects": "Hard shadow offsets (box-shadow: 4px 4px 0px #000000), tactile button press (transform: translate(2px, 2px))",
        "best_for": "Fintech for Gen-Z, modern developer tools, indie web apps, creator marketplaces, newsletters",
        "do_not_use": "Traditional healthcare, luxury fashion, corporate banking",
        "light": "✓ Full", "dark": "◐ Partial", "perf": "⚡ Excellent", "a11y": "✓ WCAG AAA", "mobile": "✓ High", "conv": "✓ Very High",
        "framework": "Tailwind 10/10, React 10/10", "era": "2020s Gumroad/Figma aesthetic", "complexity": "Low-Medium",
        "prompt": "Create a Neo-Brutalist UI with thick 2-3px solid black borders, hard unblurred drop shadows (4px 4px 0px black), vibrant pastel surfaces, and bold punchy typography.",
        "css": "border: 3px solid #000; box-shadow: 4px 4px 0px #000; border-radius: 6px; background: #fde047; font-weight: 700;",
        "checklist": "☐ 2-3px solid black borders, ☐ Hard unblurred box-shadow, ☐ Tactile active click translation, ☐ Saturated pop color palette",
        "vars": "--nb-border: 3px solid #000, --nb-shadow: 4px 4px 0px #000, --nb-bg: #fde047, --nb-radius: 6px"
    },
    {
        "name": "Bento Grid",
        "category": "Bento Grid",
        "type": "Layout Architecture",
        "keywords": "Modular compartments, asymmetric card spans, Apple-style feature boxes, visual hierarchy, micro-data displays",
        "primary": "Matte Charcoal #12141C, Deep Obsidian #08090D, Clean White #F8FAFC",
        "secondary": "Subtle border hairlines, glowing micro-accents, gradient glass highlights",
        "effects": "Smooth hover lift (-2px), subtle interior inset gradients, modular responsive card spans (grid-column: span 4/8/12)",
        "best_for": "Product feature showcases, diagnostic telemetry, modern SaaS homepages, analytics dashboards",
        "do_not_use": "Long-form linear prose reading, simple single-column documents",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "✓ WCAG AA+", "mobile": "✓ High", "conv": "✓ Very High",
        "framework": "Tailwind 10/10, CSS Grid 10/10, Next.js 10/10", "era": "2020s Apple & Linear style", "complexity": "Medium",
        "prompt": "Architect a Bento Grid UI with modular compartment cards, asymmetric column spans (e.g. 8/4, 4/4/4), subtle hairline borders, and dedicated telemetry micro-widgets.",
        "css": "display: grid; grid-template-columns: repeat(12, 1fr); gap: 16px; border: 1px solid rgba(255,255,255,0.08); border-radius: 12px;",
        "checklist": "☐ Asymmetric card spans, ☐ 12-column responsive layout, ☐ Interior micro-visualizations, ☐ Hairline border containment",
        "vars": "--bento-gap: 16px, --bento-radius: 12px, --bento-card-bg: #12141c, --bento-border: rgba(255,255,255,0.08)"
    },
    {
        "name": "Surrealism",
        "category": "Surrealism",
        "type": "Creative & Artistic",
        "keywords": "Dreamlike, bizarre juxtapositions, floating geometric solids, optical illusions, physics-defying layouts, ethereal lighting",
        "primary": "Midnight Navy #0F172A, Twilight Purple #581C87, Sunset Ochre #D97706, Cloud White #F8FAFC",
        "secondary": "Iridescent glows, deep twilight atmospheric shadows",
        "effects": "Floating physics-free transforms, surreal object blending, subtle canvas distortions, 3D WebGL floating assets",
        "best_for": "Artistic product launches, conceptual brands, high-concept portfolios, immersive storytelling",
        "do_not_use": "Standard ecommerce checkout, administrative tables, forms",
        "light": "◐ Partial", "dark": "✓ Full", "perf": "⚠ Moderate", "a11y": "⚠ Requires Care", "mobile": "◐ Medium", "conv": "◐ Medium",
        "framework": "Three.js 10/10, WebGL 10/10, GSAP 10/10", "era": "1920s Avant-Garde", "complexity": "High",
        "prompt": "Design a surrealist web experience featuring dreamlike floating compositions, impossible architectural perspectives, and atmospheric depth.",
        "css": "perspective: 1200px; transform-style: preserve-3d; filter: drop-shadow(0 20px 40px rgba(88,28,135,0.4));",
        "checklist": "☐ Dreamlike spatial layout, ☐ Unexpected object pairings, ☐ Atmospheric lighting gradients, ☐ Smooth floating animations",
        "vars": "--surreal-glow: rgba(88,28,135,0.4), --depth-perspective: 1200px"
    },
    {
        "name": "Neo-classical",
        "category": "Neo-classical",
        "type": "Luxury & Editorial",
        "keywords": "Symmetrical balance, monumental serif typography, marble tones, refined gold/bronze accents, architectural grandeur",
        "primary": "Alabaster White #FAFAF9, Deep Bronze #78350F, Obsidian Black #0C0A09, Roman Gold #D97706",
        "secondary": "Warm Marble #E7E5E4, Laurel Green #15803D",
        "effects": "Refined hairline borders, delicate serif italic headings, subtle stone-like background texture, symmetrical column grids",
        "best_for": "Luxury hospitality, high-end architecture firms, fine art galleries, premium legal & heritage brands",
        "do_not_use": "Fast-paced crypto trading, casual gaming",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "✓ WCAG AAA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10", "era": "18th Century Classical Revival", "complexity": "Medium",
        "prompt": "Design a Neo-Classical luxury layout with monumental serif typography, symmetrical structural harmony, refined warm marble palettes, and delicate gold hairline rules.",
        "css": "font-family: 'Playfair Display', 'Cormorant Garamond', serif; border: 1px solid #d4af37; letter-spacing: 0.05em; text-transform: uppercase;",
        "checklist": "☐ Symmetrical visual balance, ☐ High-craft serif typography, ☐ Refined marble/bronze accents, ☐ Architectural measure constraints",
        "vars": "--color-marble: #fafaf9, --color-bronze: #78350f, --color-gold: #d4af37, --font-serif: 'Playfair Display', serif"
    },
    {
        "name": "Scrapbook",
        "category": "Scrapbook",
        "type": "Tactile & Playful",
        "keywords": "Torn paper edges, tape overlays, polaroid frames, handwritten notes, collage layering, organic stamps, nostalgic textures",
        "primary": "Kraft Paper #D4B996, Warm Parchment #FEF3C7, Washed Charcoal #374151",
        "secondary": "Washi Tape Pastels (Mint #A7F3D0, Coral #FECDD3, Sky #BAE6FD)",
        "effects": "Rotated cards (-2deg to 3deg), masking-tape drop shadows, torn edge SVG masks, handwriting font accents",
        "best_for": "Personal travel blogs, creative lifestyle portfolios, memory journals, wedding websites, craft goods",
        "do_not_use": "Enterprise B2B tools, legal dashboards, medical portals",
        "light": "✓ Full", "dark": "✗ No", "perf": "⚡ Good", "a11y": "◐ Ensure readable text", "mobile": "✓ High", "conv": "✓ High for D2C",
        "framework": "CSS/SVG 10/10, Tailwind 9/10", "era": "Handmade Craft / Vintage", "complexity": "Medium",
        "prompt": "Create a charming scrapbook collage interface with paper textures, washi tape accents, polaroid photo frames with slight rotations, and handwritten annotations.",
        "css": "transform: rotate(-2deg); box-shadow: 0 4px 12px rgba(0,0,0,0.15); border: 8px solid #fff; font-family: 'Caveat', cursive;",
        "checklist": "☐ Organic slight card rotations, ☐ Washi tape / pin overlays, ☐ Polaroid photo borders, ☐ High-legibility body font",
        "vars": "--tape-color: rgba(167, 243, 208, 0.7), --paper-bg: #fef3c7, --font-handwriting: 'Caveat', cursive"
    },
    {
        "name": "Pixel Art",
        "category": "Pixel Art",
        "type": "Retro & Gaming",
        "keywords": "8-bit/16-bit raster grid, chunky pixel fonts, retro arcade palettes, pixelated borders, dithered shading, nostalgic gaming",
        "primary": "GameBoy Green #8BAC0F, #306230, #0F380F, or Cyber 16-bit (Neon Cyan #00FFFF, Magenta #FF00FF)",
        "secondary": "Arcade Yellow #FFCC00, Deep CRT Black #080808",
        "effects": "Image rendering: pixelated (crisp-edges), stepped frame animations (steps(4)), 8-bit chip sound feedback",
        "best_for": "Retro games, indie developer homepages, chiptune music sites, nostalgic tech blogs, web3 gaming",
        "do_not_use": "Corporate enterprise apps, medical or banking portals",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "◐ Ensure font legibility", "mobile": "✓ High", "conv": "◐ Medium",
        "framework": "Canvas/CSS 10/10, Tailwind 9/10", "era": "1980s Arcade & NES", "complexity": "Medium",
        "prompt": "Design an authentic 8-bit Pixel Art interface using a constrained 16-color arcade palette, pixelated borders, step-based sprite animations, and crisp bitmap fonts.",
        "css": "image-rendering: pixelated; font-family: 'Press Start 2P', monospace; border: 4px solid #000; box-shadow: 4px 4px 0 #000;",
        "checklist": "☐ Pixelated image rendering, ☐ Bitmap/pixel typography, ☐ Stepped frame animations, ☐ Constrained retro color palette",
        "vars": "--pixel-size: 4px, --pixel-border: 4px solid #000, --font-pixel: 'Press Start 2P', monospace"
    },
    {
        "name": "Conceptual Sketch",
        "category": "Conceptual Sketch",
        "type": "Blueprint & Wireframe",
        "keywords": "Hand-drawn wireframe lines, blueprint grid, draft pencil annotations, architectural schematics, rough strokes",
        "primary": "Blueprint Navy #1E3A8A, Graph Blue #DBEAFE, Graphite Charcoal #1F2937, Drafting White #FFFFFF",
        "secondary": "Highlighter Yellow #FEF08A, Correction Red #EF4444",
        "effects": "Rough SVG path strokes, technical dimension calipers, blueprint millimeter background grid, pencil sketch borders",
        "best_for": "Product design prototypes, architecture blueprints, engineering case studies, early-stage pitch decks",
        "do_not_use": "Finished polished ecommerce, corporate luxury consumer goods",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "✓ WCAG AA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Rough.js 10/10, SVG 10/10, Tailwind 9/10", "era": "Architectural Drafting", "complexity": "Medium",
        "prompt": "Create an architectural conceptual sketch UI featuring blueprint grid backgrounds, hand-drawn vector stroke borders, dimension calipers, and drafting annotations.",
        "css": "background-image: linear-gradient(#dbeafe 1px, transparent 1px), linear-gradient(90deg, #dbeafe 1px, transparent 1px); background-size: 20px 20px;",
        "checklist": "☐ Millimeter graph background grid, ☐ Technical dimension calipers, ☐ Blueprint color harmony, ☐ Clean readable technical typography",
        "vars": "--blueprint-bg: #1e3a8a, --grid-line: rgba(219, 234, 254, 0.2), --font-draft: 'Space Mono', monospace"
    },
    {
        "name": "Luxury Typography",
        "category": "Luxury Typography",
        "type": "Editorial & Fashion",
        "keywords": "High-contrast Didone serifs, tight tracking on titles, generous leading, scarce gold/champagne accents, editorial elegance",
        "primary": "Obsidian Black #050505, Warm Sand #F5F2EB, Pure White #FFFFFF",
        "secondary": "Champagne Gold #D4AF37, Deep Bronze #8C6D3B, Silk Charcoal #1C1917",
        "effects": "Ultra-smooth 400ms transitions, 0.5px hairline dividers, subtle parallax imagery, typographic measure constraints (45-65ch)",
        "best_for": "Haute couture fashion, luxury real estate, fine jewelry, Michelin-star dining, premium fragrance",
        "do_not_use": "Discount marketplaces, SaaS utility dashboards, children's toys",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "✓ WCAG AAA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10", "era": "High Fashion & Vogue Era", "complexity": "Low-Medium",
        "prompt": "Design an ultra-luxury editorial interface driven by high-contrast Didone serif headlines, generous whitespace, understated champagne gold accents, and magazine-quality layouts.",
        "css": "font-family: 'Bodoni Moda', 'Playfair Display', serif; letter-spacing: 0.12em; text-transform: uppercase; line-height: 1.8; max-width: 60ch;",
        "checklist": "☐ High-contrast Didone serifs, ☐ Generous whitespace (60-70%), ☐ Scarce <=3% gold accents, ☐ Magazine editorial layout",
        "vars": "--font-luxury: 'Bodoni Moda', serif, --color-gold: #d4af37, --color-sand: #f5f2eb, --color-ink: #050505"
    },
    {
        "name": "Editorial Design",
        "category": "Editorial Design",
        "type": "Magazine & Publishing",
        "keywords": "Multi-column newspaper layout, pull quotes, drop caps, dual typography friction (Sans + Expressive Serif), asymmetric measure",
        "primary": "Newsprint Off-White #FDFBF7, Deep Charcoal Ink #18181B, Signal Crimson #DC2626",
        "secondary": "Muted Slate #71717A, Warm Cream #F4EFE6",
        "effects": "1px column hairline rules, drop caps (:first-letter), formatted pull quotes with vertical rule, caption metadata tags",
        "best_for": "Digital magazines, journalism platforms, long-form investigative blogs, literary portals, research digests",
        "do_not_use": "Quick utility micro-tools, video streaming gaming portals",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Excellent", "a11y": "✓ WCAG AAA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10", "era": "Print Journalism & Broadside", "complexity": "Medium",
        "prompt": "Create a high-craft editorial publishing layout featuring multi-column text grids, elegant drop caps, highlighted pull quotes with vertical rules, and functional sans metadata.",
        "css": "column-count: 2; column-gap: 3rem; column-rule: 1px solid rgba(0,0,0,0.1); font-family: 'Newsreader', 'Lora', serif; font-size: 1.125rem;",
        "checklist": "☐ Multi-column editorial grid, ☐ Drop caps on lead paragraphs, ☐ Pull quotes styled with vertical rules, ☐ High-legibility serif body copy",
        "vars": "--font-editorial: 'Newsreader', serif, --font-meta: 'Inter', sans-serif, --newsprint-bg: #fdfbf7, --ink: #18181b"
    },
    {
        "name": "Y2K Aesthetic",
        "category": "Y2K Aesthetic",
        "type": "Retro Futuristic",
        "keywords": "Early 2000s cyber, chrome text, iridescent gradients, bubble text, frosted plastic, futuristic optimism, glitter sparkles",
        "primary": "Metallic Chrome #E2E8F0, Electric Bubblegum #F43F5E, Cyber Lime #A3E635, Baby Blue #38BDF8",
        "secondary": "Holographic Iridescence (conic-gradient rainbow), Deep Cyber Violet #4C1D95",
        "effects": "Bevel and emboss filters, animated star sparkles, metallic chrome text-shadow gradients, glowing translucent buttons",
        "best_for": "Gen-Z apparel, music producer portfolios, party events, nostalgic 2000s cultural brands",
        "do_not_use": "Government forms, corporate B2B services, medical apps",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Good", "a11y": "◐ Ensure readable text", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 9/10, CSS 10/10", "era": "Late 1990s - Early 2000s", "complexity": "Medium",
        "prompt": "Design a vibrant Y2K cyber aesthetic interface with chrome typography effects, holographic iridescent gradients, frosted bubble buttons, and early-2000s optimistic futuristic flair.",
        "css": "background: radial-gradient(circle, #38bdf8, #f43f5e); filter: drop-shadow(0 0 10px rgba(56, 189, 248, 0.6)); border-radius: 9999px;",
        "checklist": "☐ Chrome/metallic typography gradients, ☐ Holographic iridescence, ☐ Rounded bubble pill containers, ☐ Optimistic futuristic vibe",
        "vars": "--y2k-pink: #f43f5e, --y2k-blue: #38bdf8, --y2k-lime: #a3e635, --chrome-gradient: linear-gradient(180deg, #fff, #94a3b8, #fff)"
    },
    {
        "name": "Ethereal",
        "category": "Ethereal",
        "type": "Atmospheric & Calm",
        "keywords": "Soft heavenly glows, dreamy pastel gradients, translucent mist overlays, ultra-delicate typography, peaceful tranquility",
        "primary": "Cloud White #FAFAFA, Dawn Pink #FCE7F3, Celestial Lavender #EDE9FE, Sky Mist #E0F2FE",
        "secondary": "Soft Pearl Gold #FEF3C7, Ethereal Violet #8B5CF6",
        "effects": "Slow ambient pulse (12s infinite), soft Gaussian blur backdrop filters (24px), delicate low-contrast shadows",
        "best_for": "Meditation apps, sleep trackers, ambient sound platforms, luxury wellness, holistic skincare",
        "do_not_use": "High-intensity sports, emergency response tools, crypto trading",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Good", "a11y": "⚠ Ensure contrast", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Framer Motion 10/10", "era": "Modern Ambient", "complexity": "Low-Medium",
        "prompt": "Create an ethereal, heavenly interface with soft mist background blurs, tranquil lavender/pink pastel hues, delicate light typography, and floating peaceful animations.",
        "css": "backdrop-filter: blur(24px); background: radial-gradient(circle at 50% 50%, rgba(237,233,254,0.6), rgba(252,231,243,0.3));",
        "checklist": "☐ Dreamlike ambient color transitions, ☐ Soft 24px+ backdrop blurs, ☐ High readability contrast for core copy, ☐ Slow calming micro-motion",
        "vars": "--ethereal-lavender: #ede9fe, --ethereal-pink: #fce7f3, --ethereal-blur: 24px"
    },
    {
        "name": "Bohemian",
        "category": "Bohemian",
        "type": "Organic & Earthy",
        "keywords": "Earthy warm terracotta, olive green, mustard yellow, organic curved shapes, botanical flourishes, artisan craft",
        "primary": "Terracotta #C2410C, Olive Green #65A30D, Mustard Ochre #CA8A04, Raw Clay #78350F",
        "secondary": "Warm Linen #FBF7EE, Desert Sand #E7D8C9",
        "effects": "Organic curved archways (border-radius: 120px 120px 0 0), handmade botanical SVG accents, warm textured paper backgrounds",
        "best_for": "Artisan craft stores, interior design studios, wellness retreats, organic food & wine, sustainable fashion",
        "do_not_use": "Cybersecurity software, industrial tech tools, financial data terminals",
        "light": "✓ Full", "dark": "◐ Partial", "perf": "⚡ Excellent", "a11y": "✓ WCAG AA+", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10", "era": "Boho Artisan Movement", "complexity": "Medium",
        "prompt": "Design a warm Bohemian artisan website with terracotta and olive earthy palettes, architectural arched photo frames, botanical vector details, and natural linen textures.",
        "css": "border-radius: 140px 140px 12px 12px; background: #fbf7ee; color: #78350f; font-family: 'DM Serif Display', serif;",
        "checklist": "☐ Earthy terracotta & olive palette, ☐ Architectural arch frames, ☐ Organic rounded forms, ☐ High-craft natural feel",
        "vars": "--color-terracotta: #c2410c, --color-olive: #65a30d, --color-linen: #fbf7ee, --font-boho: 'DM Serif Display', serif"
    },
    {
        "name": "Cyberpunk",
        "category": "Cyberpunk",
        "type": "Sci-Fi & Futuristic",
        "keywords": "High-contrast neon, neon yellow/cyan/magenta, dark dystopian matrix, terminal monospace, glitch displacement, HUD telemetry",
        "primary": "Cyber Yellow #FEE500, Neon Cyan #00F0FF, Hot Magenta #FF003C, Deep Matrix Black #05050A",
        "secondary": "Circuit Grid Lines #1E293B, Toxic Green #39FF14",
        "effects": "Glitch keyframe displacement (skewX/clip-path), neon text-shadow glows, corner chamfer cuts (clip-path polygon), scanlines overlay",
        "best_for": "Gaming platforms, hacker tools, web3 decentralized protocols, sci-fi media, tech hardware showcase",
        "do_not_use": "Healthcare clinical tools, corporate legal firms, conservative banking",
        "light": "✗ No", "dark": "✓ Full (Only)", "perf": "⚡ Good", "a11y": "⚠ Ensure contrast", "mobile": "✓ High", "conv": "✓ High for tech",
        "framework": "Tailwind 10/10, CSS 10/10, GSAP 10/10", "era": "1980s Cyberpunk / 2077", "complexity": "Medium-High",
        "prompt": "Design an intense Cyberpunk HUD interface with sharp chamfered corner containers, electric neon yellow/cyan/magenta accents, dark matrix backgrounds, and live telemetry monospace readouts.",
        "css": "clip-path: polygon(0 0, calc(100% - 15px) 0, 100% 15px, 100% 100%, 15px 100%, 0 calc(100% - 15px)); background: #05050a; border: 1px solid #00f0ff;",
        "checklist": "☐ Chamfered corner polygons, ☐ Neon cyan/yellow glows, ☐ Monospace technical HUD readouts, ☐ Deep matrix contrast",
        "vars": "--cyber-yellow: #fee500, --cyber-cyan: #00f0ff, --cyber-magenta: #ff003c, --cyber-bg: #05050a"
    },
    {
        "name": "Anthropomorphic",
        "category": "Anthropomorphic",
        "type": "Character & Emotive",
        "keywords": "Character-driven UI, expressive eye tracking, humanized mascots, responsive emotional states, playful avatars",
        "primary": "Warm Apricot #FB923C, Friendly Sky #38BDF8, Soft Charcoal #1E293B, Cheerful Yellow #FDE047",
        "secondary": "Emotional status tints (Blush Pink #F472B6, Serene Mint #4ADE80)",
        "effects": "Cursor-tracking mascot eyes, interactive reactive animations on input focus, bouncy spring physics (cubic-bezier(0.34, 1.56, 0.64, 1))",
        "best_for": "Interactive AI assistants, children's education, gamified language learning, onboarding guides",
        "do_not_use": "Solemn medical diagnostics, enterprise data security compliance",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Good", "a11y": "✓ WCAG AA", "mobile": "✓ High", "conv": "✓ Very High",
        "framework": "Rive 10/10, Lottie 10/10, Framer Motion 10/10", "era": "Modern Character UX", "complexity": "Medium-High",
        "prompt": "Create an emotive, anthropomorphic interface where friendly animated character mascots react to user actions, track mouse focus with their eyes, and guide onboarding.",
        "css": "transition: transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1); border-radius: 24px; filter: drop-shadow(0 8px 16px rgba(0,0,0,0.1));",
        "checklist": "☐ Expressive mascot state animations, ☐ Bouncy spring physics on interaction, ☐ Clear friendly color hierarchy, ☐ Delightful feedback",
        "vars": "--mascot-color: #fb923c, --spring-curve: cubic-bezier(0.34, 1.56, 0.64, 1)"
    },
    {
        "name": "Victorian",
        "category": "Victorian",
        "type": "Heritage & Vintage",
        "keywords": "Intricate filigree engravings, ornate decorative borders, deep jewel tones (Emerald, Ruby, Navy), vintage woodcut illustrations",
        "primary": "Imperial Navy #0F172A, Deep Ruby #881337, Antique Gold #D97706, Forest Emerald #064E3B",
        "secondary": "Aged Parchment #FEF3C7, Burnished Brass #B45309",
        "effects": "Ornate engraved border corners, drop-shadowed antique gold typography, woodcut crosshatch shading, flourish dividers",
        "best_for": "Artisanal spirits & distilleries, heritage tobacco/tea brands, escape rooms, historical fiction & museums",
        "do_not_use": "Modern SaaS apps, agile sprint management tools",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Good", "a11y": "✓ WCAG AA+", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 9/10, SVG 10/10", "era": "19th Century Victorian Era", "complexity": "Medium",
        "prompt": "Design an ornate Victorian heritage interface with intricate filigree border flourishes, deep emerald and ruby jewel tones, antique gold typography, and vintage engraving details.",
        "css": "border: 4px double #d97706; font-family: 'Cinzel Decorative', 'Playfair Display', serif; background-color: #0f172a; color: #fef3c7;",
        "checklist": "☐ Double/filigree border frames, ☐ Deep jewel-tone palette, ☐ Antique serif typography, ☐ Woodcut or engraved flourishes",
        "vars": "--victorian-gold: #d97706, --victorian-ruby: #881337, --victorian-navy: #0f172a, --font-victorian: 'Cinzel Decorative', serif"
    },
    {
        "name": "Cybercore",
        "category": "Cybercore",
        "type": "Futuristic Subculture",
        "keywords": "Translucent dark glass, digital wireframe meshes, technical monospace HUD, laser cyan and violet highlights, high-tech minimalism",
        "primary": "Obsidian Deep #030712, Laser Cyan #22D3EE, Plasma Violet #A855F7, Steel Grey #94A3B8",
        "secondary": "Subtle wireframe grid lines, translucent dark slate panels",
        "effects": "1px precision cyan borders with corner crosshairs, 3D wireframe rotating geometry, glowing data stream pulses",
        "best_for": "Autonomous AI agent dashboards, cybersecurity threat maps, web3 developer tools, hardware interfaces",
        "do_not_use": "Children's storybooks, pastoral organic food blogs",
        "light": "✗ No", "dark": "✓ Full (Only)", "perf": "⚡ Excellent", "a11y": "✓ WCAG AA+", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10, Three.js 9/10", "era": "2020s Cyberpunk Subculture", "complexity": "Medium",
        "prompt": "Build a Cybercore tech UI featuring razor-thin laser cyan borders, corner crosshair target markers, translucent obsidian cards, and technical data stream telemetry.",
        "css": "background: rgba(3, 7, 18, 0.85); border: 1px solid rgba(34, 211, 238, 0.3); backdrop-filter: blur(12px); font-family: 'JetBrains Mono', monospace;",
        "checklist": "☐ Laser cyan/violet accents, ☐ Corner crosshairs / target markers, ☐ Monospace telemetry data, ☐ Translucent obsidian cards",
        "vars": "--cybercore-cyan: #22d3ee, --cybercore-violet: #a855f7, --cybercore-bg: #030712"
    },
    {
        "name": "Synthwave",
        "category": "Synthwave",
        "type": "Retro 80s Nostalgia",
        "keywords": "Neon sunset wireframe grid, glowing magenta and cyan, chrome retro typography, 80s outrun horizon, palm tree silhouettes",
        "primary": "Hot Neon Pink #FF007F, Electric Sunset Orange #FF8800, Cyber Cyan #00F0FF, Deep Space Purple #1A0B2E",
        "secondary": "Grid Horizon Violet #3B0764, Chrome Silver #E2E8F0",
        "effects": "Perspective 3D animated grid horizon (transform: perspective(300px) rotateX(60deg)), glowing sun radial gradient, scanline CRT overlay",
        "best_for": "Music visualizers, 80s retro games, podcast sites, synthwave music labels, creative events",
        "do_not_use": "Serious corporate B2B enterprise software, government portals",
        "light": "✗ No", "dark": "✓ Full (Only)", "perf": "⚡ Good", "a11y": "⚠ Requires Care", "mobile": "✓ High", "conv": "✓ High for niche",
        "framework": "CSS 3D 10/10, Tailwind 9/10, Three.js 9/10", "era": "1980s Outrun / Synthwave", "complexity": "Medium",
        "prompt": "Create an 80s Synthwave Outrun interface with an animated perspective neon grid floor, giant glowing magenta/orange horizon sun, and metallic chrome text.",
        "css": "background: linear-gradient(180deg, #1a0b2e 0%, #ff007f 60%, #ff8800 100%); text-shadow: 0 0 12px #00f0ff;",
        "checklist": "☐ 3D perspective grid floor, ☐ Glowing magenta/orange sunset gradient, ☐ Neon glowing text-shadow, ☐ 80s chrome title font",
        "vars": "--synth-pink: #ff007f, --synth-orange: #ff8800, --synth-cyan: #00f0ff, --synth-dark: #1a0b2e"
    },
    {
        "name": "Graffiti",
        "category": "Graffiti & Street Art",
        "type": "Urban & Expressive",
        "keywords": "Street art spray paint textures, drip effects, bold stencil typography, raw concrete backgrounds, expressive rebellious energy",
        "primary": "Spray Can Neon Green #22C55E, Electric Pink #EC4899, Hazard Yellow #EAB308, Concrete Grey #374151",
        "secondary": "Matte Asphalt #18181B, Dripping Paint White #FFFFFF",
        "effects": "SVG spray splatter masks, paint drip overflow, rotated skewed tag badges, concrete texture background overlays",
        "best_for": "Streetwear fashion brands, skate culture, hip-hop music platforms, youth sports events, rebellious indie brands",
        "do_not_use": "Corporate accounting, banking, medical clinics",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Good", "a11y": "◐ Keep text readable", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 9/10, SVG 10/10", "era": "Urban Street Art Culture", "complexity": "Medium",
        "prompt": "Design an edgy street-art Graffiti UI featuring raw concrete backgrounds, spray paint stencil headlines, vibrant neon paint drips, and skewed sticker badges.",
        "css": "transform: rotate(-3deg) skew(-2deg); font-family: 'Permanent Marker', cursive; text-shadow: 3px 3px 0px #000;",
        "checklist": "☐ Stencil or marker display typography, ☐ Spray splatter / drip details, ☐ Concrete/asphalt backdrop texture, ☐ High street energy",
        "vars": "--spray-green: #22c55e, --spray-pink: #ec4899, --font-street: 'Permanent Marker', cursive"
    },
    {
        "name": "Gothic",
        "category": "Gothic",
        "type": "Dark & Atmospheric",
        "keywords": "Blackletter calligraphy, cathedral pointed arches, dramatic shadows, blood crimson and silver accents, dark romantic mood",
        "primary": "Abyssal Black #09090B, Blood Crimson #991B1B, Antique Silver #CBD5E1, Charcoal Shadow #18181B",
        "secondary": "Deep Velvet Violet #2E1065, Pewter #64748B",
        "effects": "Pointed cathedral arch containers (clip-path), subtle silver metallic specular highlights, dramatic chiaroscuro lighting",
        "best_for": "Dark fantasy games, gothic fashion, heavy metal & darkwave music, horror storytelling, occult literature",
        "do_not_use": "Baby care products, upbeat corporate productivity SaaS",
        "light": "✗ No", "dark": "✓ Full (Only)", "perf": "⚡ Excellent", "a11y": "✓ WCAG AA+", "mobile": "✓ High", "conv": "✓ High for niche",
        "framework": "Tailwind 10/10, CSS 10/10", "era": "Medieval Gothic & Romanticism", "complexity": "Medium",
        "prompt": "Design a dramatic Gothic dark interface with pointed cathedral arch geometries, blackletter display headings, deep blood crimson accents, and silver hairline rules.",
        "css": "font-family: 'UnifrakturMaguntia', 'Cinzel', serif; border: 1px solid rgba(203, 213, 225, 0.2); background: #09090b; color: #cbd5e1;",
        "checklist": "☐ Gothic/Blackletter display font, ☐ Pointed arch geometry, ☐ Crimson and silver accents, ☐ Deep atmospheric dark mode",
        "vars": "--gothic-black: #09090b, --gothic-crimson: #991b1b, --gothic-silver: #cbd5e1, --font-gothic: 'Cinzel', serif"
    },
    {
        "name": "Mixed Media",
        "category": "Mixed Media",
        "type": "Eclectic & Multi-Layered",
        "keywords": "Collage of digital photography, tactile physical paper, hand-drawn charcoal strokes, vector geometric shapes, multi-texture blending",
        "primary": "Raw Canvas #F4F1EA, Pitch Black #0F0F11, Vermilion Red #EF4444, Electric Ultramarine #1D4ED8",
        "secondary": "Textured Kraft #E5E0D8, Neon Highlighter Yellow #FACC15",
        "effects": "Multi-blend modes (mix-blend-mode: multiply / overlay), overlapping photographic and vector layers, tactile paper grain texture",
        "best_for": "Contemporary art galleries, boundary-pushing creative agencies, high-concept portfolios, avant-garde music",
        "do_not_use": "Standard administrative data entry, high-speed trading terminals",
        "light": "✓ Full", "dark": "✓ Full", "perf": "⚡ Good", "a11y": "✓ WCAG AA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "CSS Blend Modes 10/10, Tailwind 10/10", "era": "Contemporary Mixed Media", "complexity": "High",
        "prompt": "Create an artistic Mixed Media collage interface combining raw canvas textures, cut-out photography, vector geometric forms, and expressive hand-drawn accents.",
        "css": "mix-blend-mode: multiply; background-image: radial-gradient(#1d4ed8 15%, transparent 16%); filter: contrast(1.1);",
        "checklist": "☐ Multi-texture collage composition, ☐ Contrast between photo and vector, ☐ Expressive typography mix, ☐ Cohesive artistic rhythm",
        "vars": "--mixed-canvas: #f4f1ea, --mixed-blue: #1d4ed8, --mixed-red: #ef4444"
    },
    {
        "name": "Wabi Sabi",
        "category": "Wabi Sabi",
        "type": "Organic & Zen",
        "keywords": "Appreciation of imperfection, natural earth tones, organic raw ceramics, Japanese minimalism, asymmetric harmony, tranquil soul",
        "primary": "Earthy Clay #A89F91, Natural Linen #F5F2EB, Charcoal Sumi Ink #262624, Muted Moss #6B705C",
        "secondary": "Warm Terracotta #B7695C, Raw Stone #DDBEA9",
        "effects": "Kintsugi gold fracture lines, subtle handmade paper grain, gentle breathing fades, organic asymmetrical layouts",
        "best_for": "Tea culture, handmade ceramics, meditation & zen spaces, mindful luxury, slow living publications",
        "do_not_use": "High-adrenaline gaming, flashy neon casino apps",
        "light": "✓ Full", "dark": "◐ Partial", "perf": "⚡ Excellent", "a11y": "✓ WCAG AAA", "mobile": "✓ High", "conv": "✓ High",
        "framework": "Tailwind 10/10, Next.js 10/10", "era": "Traditional Japanese Philosophy", "complexity": "Low-Medium",
        "prompt": "Design a serene Wabi Sabi interface celebrating natural imperfection: muted clay and stone earth tones, Sumi ink typography, asymmetrical balance, and delicate Kintsugi gold fracture details.",
        "css": "background: #f5f2eb; color: #262624; font-family: 'Shippori Mincho', 'Noto Serif JP', serif; line-height: 1.9; letter-spacing: 0.04em;",
        "checklist": "☐ Natural earth & linen palette, ☐ Asymmetric zen balance, ☐ Restrained Sumi ink typography, ☐ Kintsugi gold hairline accents",
        "vars": "--wabi-linen: #f5f2eb, --wabi-clay: #a89f91, --wabi-ink: #262624, --wabi-kintsugi: #d4af37, --font-zen: 'Shippori Mincho', serif"
    }
]

print(f"Loaded {len(DESIGN_LANGUAGES_29)} curated design languages.")
